version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2021-10-23T03-28-24Z
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    expose:
      - "9000"
      - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_URL: "http://localhost:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=cpic_db
      - MYSQL_USER=cpic
      - MYSQL_PASSWORD=cpic
    ports:
      - 3306:3306

volumes:
  minio-data:
