#!/bin/sh
OPENAPI_FILE=interface.yaml
packageName=cpic_interface
packageVersion=1.0.0
serverPort=3001

openapi-generator generate \
-i ${OPENAPI_FILE} \
-g python-flask \
-o stub-flask \
--additional-properties=packageName=${packageName} \
--additional-properties=packageVersion=${packageVersion} \
--additional-properties=serverPort=${serverPort}