openapi: 3.0.1
info:
  title: 医审平台案件提交接口
  version: 1.0.0

servers:
  - url: http://localhost:3001

paths:
  /createCase:
    post:
      summary: 用于接收渠道推送的案件信息
      operationId: createCase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCaseDto"
            example:
              custid: "21"
              uuid: "ef30e1ca-9888-451d-a328-08bfc6a7d482"
              token: "Encrypted Payload（加密后的数据）"
      responses:
        "200":
          description: 推送案件成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResDto"
              example:
                code: 200
                data: "9"

  /queryCase:
    post:
      summary: 查询任务状态，及识别结果
      operationId: queryCase
      responses:
        "200":
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResDto"
              example:
                code: 200
                data: "9"

components:
  schemas:
    ResDto:
      type: object
      properties:
        code:
          type: integer
          description: 结果代码。200：推送成功
        msg:
          type: string
          description: 发生错误时，返回错误信息。成功时，不返回该字段。
        data:
          type: string
          description: 成功时，返回任务序号 / 案件号。错误时，不返回该字段。

    CreateCaseDto:
      type: object
      properties:
        custid:
          type: string
          description: 客户渠道 ID
        uuid:
          type: string
          description: 标识本次请求的唯一标识，用于客户确认医审结果。由客户端保证唯一性
        token:
          type: string
          description: |
            经过加密后的案件数据信息。

            ## 加密方案
            ---

            为了保证数据的安全性，案件数据采用 `aes-256-ecb` 加密，加密结果使用 `base64` 编码。

            ### 1. 原始的案件详情数据结构

            原始的案件详情数据结构请参考：*CaseDetailDto*

            ### 2. 由平台方分配给用户的参数

            | 参数名 | 描述 | 给广东太保分配的值 |
            |:-------|:-----|:-----------------:|
            | custid | 用户渠道 ID | 21 |
            | appkey | 用户授权码 | asdfghjkl |
            | secretkey | 用户安全码 | dwsuhfci |
            | salt | 加密密钥明文 | gdtb |

            ### 3. 密钥

            `aes-256-ecb` 加密需要 32bits 的密钥，因此使用 `md5(salt).digest("hex")` 作为加密密钥。

            ### 4. 加密

            Node.js 示例：

            ```javascript
            const crypto = require("crypto");

            const md5 = crypto.createHash("md5");
            const cipher = crypto.createCipheriv(
              "aes-256-ecb",
              md5.update(salt).digest("hex"),
              ""
            );
            tokenCipher = cipher.update(JSON.stringify(token), "base64");
            tokenCipher += cipher.final("base64");
            ```

    ImageDetailDto:
      type: object
      properties:
        id:
          type: string
          description: 图片序号，在本案件中唯一。由客户端保证唯一性
        name:
          type: string
          description: 图片的名称。
        url:
          type: string
          description: 图片的 URL

    CaseDetailDto:
      type: object
      properties:
        appkey:
          type: string
          description: 给渠道客户分配的授权码。
        images:
          type: array
          description: 案件资料图片数组
          items:
            $ref: "#/components/schemas/ImageDetailDto"
        insurecode:
          type: string
          description: 被保险人身份证号
        insureName:
          type: string
          description: 被保险人姓名
        registNo:
          type: string
          description: 报案号
        sign:
          type: string
          description: |
            签名，用以校验参数是否被篡改。

            **计算方法**：

            ```
            md5(appkey+registno+timestamp+uuid+secretkey).digest("hex")
            ```
        timestamp:
          type: string
          description: 接口调用时间
        weight:
          type: integer
          description: 任务权重，默认为3，加急任务请设置为5。
        zmark:
          type: string
          description: 保留字段，用于自定义信息，目前未使用。

    QueryCaseResDto:
      type: object
      properties:
        code:
          type: string
          description: 结果代码。200：查询成功
        msg:
          type: string
          description: 发生错误时，返回错误信息。成功时，不返回该字段。
        uuid:
          type: string
          description: 创建任务时，由创建方生成的任务唯一标识。
        data:
          type: object
          description: 查询结果
          properties:
            case_state:
              type: object
              properties:
                uploadTime:
                  type: string
                  description: 任务的上传时间
                state:
                  type: integer
                  description: 任务状态。0：尚未开始；1：处理中；2：处理完成
                zmark:
                  type: string
                  description: 来自前置平台的备注
                ymark:
                  type: string
                  description: 来自识别平台的备注
            case_info:
              type: object
              properties:
                caseNo:
                  type: string
                  description: 任务号
                registNo:
                  type: string
                  description: 报案号
                insureName:
                  type: string
                  description: 被保险人姓名
                insurecode:
                  type: string
                  description: 被保险人身份证号
                costType:
                  type: string
                  description: 费用类型
                  enum:
                    - 门诊
                    - 住院
                    - 外购药
                invoiceTotalAmount:
                  type: number
                  description: 案件下所有发票的总金额
                admissionDate:
                  type: string
                  description: 入院日期
                dischargeDate:
                  type: string
                  description: 出院日期
                hospitalizationDays:
                  type: number
                  description: 住院天数
                invoiceList:
                  type: array
                  description: 发票详情列表
                  items:
                    type: object
                    properties:
                      invoiceNumber:
                        type: string
                        description: 发票号码
                      invoiceName:
                        type: string
                        description: 发票名称
                      invoiceAmount:
                        type: number
                        description: 发票金额
                      invoiceDate:
                        type: string
                        description: 开票日期
                      hospital:
                        type: string
                        description: 医院名称或外购药开票单位名称
                      hospitalGrade:
                        type: string
                        description: 医院等级
                        enum:
                          - 三级甲等
                          - 三级乙等
                          - 三级丙等
                          - 二级甲等
                          - 二级乙等
                          - 二级丙等
                          - 一级甲等
                          - 一级乙等
                          - 一级丙等
                          - 其它
                      reimbursementAmount:
                        type: number
                        description: 医保报销金额
                      basicMedicalInsuranceAmount:
                        type: number
                        description: 基本医保范围内金额
                      allExpenseAmount:
                        type: number
                        description: 全部自费金额
                      allExpenseSource:
                        type: string
                        description: 全部自费金额来源
                        enum:
                          - 清单
                          - 发票
                          - 结算单
                      partsExpenseAmount:
                        type: number
                        description: 部分自费金额
                      partsExpenseSource:
                        type: number
                        description: 部分自费金额来源
                        enum:
                          - 清单
                          - 发票
                          - 结算单
                      thirdPartyHasPaidAmount:
                        type: number
                        description: 第三方支付金额
            result:
              type: array
              items:
                type: object
                properties:
                  imageId:
                    type: string
                    description: 图片 ID
                  imageName:
                    type: string
                    description: 图片名称
                  moreThanOneList:
                    type: number
                    description: 是否一图多票。1：是；2：否
                  remark:
                    type: string
                    description: 备注
                  details1:
                    type: array
                    description: 发票返回值。如果一图多票，则返回多个数组元素。
                    items:
                      $ref: "#/components/schemas/InvoiceDetailDto"

    InvoiceDetailDto:
      type: object
      properties:
        imageType:
          type: number
          description: 图片类型。在 `details1` 中始终为 `1`
        imageClassification:
          type: string
          description: 图片分类
          enum:
            - 门诊发票
            - 住院发票
            - 外购药发票
            - 门诊清单
            - 住院清单
            - 结算单
            - 其它
        invoiceName:
          type: string
          description: 发票名称
        hospital:
          type: string
          description: 医院名称或外购药开票单位名称
        hospitalGrade:
          type: string
          description: 医院等级
          enum:
            - 三级甲等
            - 三级乙等
            - 三级丙等
            - 二级甲等
            - 二级乙等
            - 二级丙等
            - 一级甲等
            - 一级乙等
            - 一级丙等
            - 其它
        name:
          type: string
          description: 发票上的姓名
        invoiceNumber:
          type: string
          description: 发票号
        invoiceDate:
          type: string
          description: 发票日期
        invoiceAmount:
          type: number
          description: 发票金额
        admissionDate:
          type: string
          description: 入院日期
        dischargeDate:
          type: string
          description: 出院日期
        reimbursementAmount:
          type: number
          description: 医保统筹金额
        remark:
          type: string
          description: 备注
