# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cpic_interface.models.base_model_ import Model
from cpic_interface.models.original_case_detail_dto import OriginalCaseDetailDto
from cpic_interface import util

from cpic_interface.models.original_case_detail_dto import OriginalCaseDetailDto  # noqa: E501

class CreateCaseResDtoData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, case_no=None, case_info=None):  # noqa: E501
        """CreateCaseResDtoData - a model defined in OpenAPI

        :param case_no: The case_no of this CreateCaseResDtoData.  # noqa: E501
        :type case_no: str
        :param case_info: The case_info of this CreateCaseResDtoData.  # noqa: E501
        :type case_info: OriginalCaseDetailDto
        """
        self.openapi_types = {
            'case_no': str,
            'case_info': OriginalCaseDetailDto
        }

        self.attribute_map = {
            'case_no': 'caseNo',
            'case_info': 'caseInfo'
        }

        self._case_no = case_no
        self._case_info = case_info

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCaseResDtoData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateCaseResDto_data of this CreateCaseResDtoData.  # noqa: E501
        :rtype: CreateCaseResDtoData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def case_no(self):
        """Gets the case_no of this CreateCaseResDtoData.

        创建案件成功时，返回案件号。由服务端创建，全局唯一。  # noqa: E501

        :return: The case_no of this CreateCaseResDtoData.
        :rtype: str
        """
        return self._case_no

    @case_no.setter
    def case_no(self, case_no):
        """Sets the case_no of this CreateCaseResDtoData.

        创建案件成功时，返回案件号。由服务端创建，全局唯一。  # noqa: E501

        :param case_no: The case_no of this CreateCaseResDtoData.
        :type case_no: str
        """

        self._case_no = case_no

    @property
    def case_info(self):
        """Gets the case_info of this CreateCaseResDtoData.


        :return: The case_info of this CreateCaseResDtoData.
        :rtype: OriginalCaseDetailDto
        """
        return self._case_info

    @case_info.setter
    def case_info(self, case_info):
        """Sets the case_info of this CreateCaseResDtoData.


        :param case_info: The case_info of this CreateCaseResDtoData.
        :type case_info: OriginalCaseDetailDto
        """

        self._case_info = case_info
