# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cpic_interface.models.base_model_ import Model
from cpic_interface.models.create_case_res_dto_data import CreateCaseResDtoData
from cpic_interface import util

from cpic_interface.models.create_case_res_dto_data import CreateCaseResDtoData  # noqa: E501

class CreateCaseResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, msg=None, data=None):  # noqa: E501
        """CreateCaseResDto - a model defined in OpenAPI

        :param code: The code of this CreateCaseResDto.  # noqa: E501
        :type code: int
        :param msg: The msg of this CreateCaseResDto.  # noqa: E501
        :type msg: str
        :param data: The data of this CreateCaseResDto.  # noqa: E501
        :type data: CreateCaseResDtoData
        """
        self.openapi_types = {
            'code': int,
            'msg': str,
            'data': CreateCaseResDtoData
        }

        self.attribute_map = {
            'code': 'code',
            'msg': 'msg',
            'data': 'data'
        }

        self._code = code
        self._msg = msg
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCaseResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateCaseResDto of this CreateCaseResDto.  # noqa: E501
        :rtype: CreateCaseResDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this CreateCaseResDto.

        结果代码。200：推送成功  # noqa: E501

        :return: The code of this CreateCaseResDto.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this CreateCaseResDto.

        结果代码。200：推送成功  # noqa: E501

        :param code: The code of this CreateCaseResDto.
        :type code: int
        """

        self._code = code

    @property
    def msg(self):
        """Gets the msg of this CreateCaseResDto.

        发生错误时，返回错误信息。成功时，不返回该字段。  # noqa: E501

        :return: The msg of this CreateCaseResDto.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this CreateCaseResDto.

        发生错误时，返回错误信息。成功时，不返回该字段。  # noqa: E501

        :param msg: The msg of this CreateCaseResDto.
        :type msg: str
        """

        self._msg = msg

    @property
    def data(self):
        """Gets the data of this CreateCaseResDto.


        :return: The data of this CreateCaseResDto.
        :rtype: CreateCaseResDtoData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CreateCaseResDto.


        :param data: The data of this CreateCaseResDto.
        :type data: CreateCaseResDtoData
        """

        self._data = data
