# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cpic_interface.models.base_model_ import Model
from cpic_interface import util


class ImageTypeDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_type=None, image_classification=None):  # noqa: E501
        """ImageTypeDto - a model defined in OpenAPI

        :param image_type: The image_type of this ImageTypeDto.  # noqa: E501
        :type image_type: str
        :param image_classification: The image_classification of this ImageTypeDto.  # noqa: E501
        :type image_classification: str
        """
        self.openapi_types = {
            'image_type': str,
            'image_classification': str
        }

        self.attribute_map = {
            'image_type': 'imageType',
            'image_classification': 'imageClassification'
        }

        self._image_type = image_type
        self._image_classification = image_classification

    @classmethod
    def from_dict(cls, dikt) -> 'ImageTypeDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageTypeDto of this ImageTypeDto.  # noqa: E501
        :rtype: ImageTypeDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_type(self):
        """Gets the image_type of this ImageTypeDto.

        图片类型。  # noqa: E501

        :return: The image_type of this ImageTypeDto.
        :rtype: str
        """
        return self._image_type

    @image_type.setter
    def image_type(self, image_type):
        """Sets the image_type of this ImageTypeDto.

        图片类型。  # noqa: E501

        :param image_type: The image_type of this ImageTypeDto.
        :type image_type: str
        """
        allowed_values = ["发票", "清单", "结算单", "其它"]  # noqa: E501
        if image_type not in allowed_values:
            raise ValueError(
                "Invalid value for `image_type` ({0}), must be one of {1}"
                .format(image_type, allowed_values)
            )

        self._image_type = image_type

    @property
    def image_classification(self):
        """Gets the image_classification of this ImageTypeDto.

        图片分类  # noqa: E501

        :return: The image_classification of this ImageTypeDto.
        :rtype: str
        """
        return self._image_classification

    @image_classification.setter
    def image_classification(self, image_classification):
        """Sets the image_classification of this ImageTypeDto.

        图片分类  # noqa: E501

        :param image_classification: The image_classification of this ImageTypeDto.
        :type image_classification: str
        """
        allowed_values = ["门诊发票", "住院发票", "外购药发票", "门诊清单", "住院清单", "结算单", "其它"]  # noqa: E501
        if image_classification not in allowed_values:
            raise ValueError(
                "Invalid value for `image_classification` ({0}), must be one of {1}"
                .format(image_classification, allowed_values)
            )

        self._image_classification = image_classification
