# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cpic_interface.models.base_model_ import Model
from cpic_interface import util


class OriginalImageDetailDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, url=None):  # noqa: E501
        """OriginalImageDetailDto - a model defined in OpenAPI

        :param id: The id of this OriginalImageDetailDto.  # noqa: E501
        :type id: str
        :param name: The name of this OriginalImageDetailDto.  # noqa: E501
        :type name: str
        :param url: The url of this OriginalImageDetailDto.  # noqa: E501
        :type url: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'url': 'url'
        }

        self._id = id
        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'OriginalImageDetailDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OriginalImageDetailDto of this OriginalImageDetailDto.  # noqa: E501
        :rtype: OriginalImageDetailDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this OriginalImageDetailDto.

        图片序号，在本案件中唯一。由客户端保证唯一性  # noqa: E501

        :return: The id of this OriginalImageDetailDto.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OriginalImageDetailDto.

        图片序号，在本案件中唯一。由客户端保证唯一性  # noqa: E501

        :param id: The id of this OriginalImageDetailDto.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OriginalImageDetailDto.

        图片的名称。  # noqa: E501

        :return: The name of this OriginalImageDetailDto.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OriginalImageDetailDto.

        图片的名称。  # noqa: E501

        :param name: The name of this OriginalImageDetailDto.
        :type name: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this OriginalImageDetailDto.

        图片的 URL  # noqa: E501

        :return: The url of this OriginalImageDetailDto.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this OriginalImageDetailDto.

        图片的 URL  # noqa: E501

        :param url: The url of this OriginalImageDetailDto.
        :type url: str
        """

        self._url = url
